### ISSUE TITLE
Make {{proof}} available in base64url format, for challenge-tls-alpn-01.

### ISSUE THREAD

**Issue by skofisk** [breard-r/acmed#129]
The ualpn daemon from uacme can pass through connections on port 443. To use it, I need to have `{{proof}}` available in a different format.

uacme/ualpn: https://github.com/ndilieto/uacme#tls-alpn-01-challenge-support
man page for ualpn, with examples: https://ndilieto.github.io/uacme/ualpn.html

Need the proof encoded in base64url format, when using challenge-tls-alpn-01.
Having it available as  `{{proof_b64u}}` or some other identifier would make it work.

Right now I make this work by using a script to crop and reencode {{proof}}, and run ualpn. But would like to use ualpn directly.
```
[[hook]]
name = "ualpn-auth"
type = ["challenge-tls-alpn-01"]
cmd = "/etc/acmed/fix-ualpn.php"
stdin_str = "auth {{identifier_tls_alpn}} {{proof}}"

[[hook]]
name = "ualpn-auth-need-patch"
type = ["challenge-tls-alpn-01"]
cmd = "/usr/bin/ualpn"
stdin_str = "auth {{identifier_tls_alpn}} {{proof_b64u}}"

[[hook]]
name = "ualpn-unauth"
type = ["challenge-tls-alpn-01-clean"]
cmd = "/usr/bin/ualpn"
stdin_str = "unauth {{identifier_tls_alpn}}"

[[group]]
name = "ualpn"
hooks = [
    "ualpn-auth",
    "ualpn-unauth",
]
```

script:
```
#!/usr/bin/php
<?php

function base64url_encode($data) {
  $b64 = base64_encode($data);
  $url = strtr($b64, '+/', '-_');
  return rtrim($url, '=');
}

$line = trim(fgets(STDIN)); // reads one line from STDIN
$lines = explode(" ", $line);

$len = strlen("1.3.6.1.5.5.7.1.31=critical,DER:04:20");
$cert = substr($lines[2], $len);
$cert = str_replace(":", "", $cert);
$cert = hex2bin($cert);
$lines[2] = base64url_encode($cert);

$fixed = vsprintf("%s %s %s\n", $lines);

$ualpn = popen("/usr/bin/ualpn", "w");
fwrite($ualpn, $fixed); // pipe fixed string to ualpn
fclose($ualpn);
```

**Comment by breard-r** [comment]
Indeed, I don't know why I haven't done it from the start. I just pushed a commit that should expose a new variable named `raw_proof`.

Can you confirm me that it works before I release a new version please?

**Comment by skofisk** [comment]
The needed data is exposed, and its in the correct format.

Also need a newline at the end of stdin_str. maybe make this built in?
stdin_str = "auth {{identifier_tls_alpn}} {{raw_proof}}\n"

Other than a bug in ualpn, it works now. (it always returns exit(1), https://github.com/ndilieto/uacme/issues/76)

**Comment by breard-r** [comment]
> Also need a newline at the end of stdin_str. maybe make this built in? stdin_str = "auth {{identifier_tls_alpn}} {{raw_proof}}\n"
> 

It should already work since it's part of the [TOML specification](https://toml.io/en/v1.0.0#string).

If not, I'll have to investigate why. In the meantime, you may use the following form:

``` toml
stdin_str = """auth {{identifier_tls_alpn}} {{raw_proof}}
"""
```

**Comment by skofisk** [comment]
Worded that a bit wrong, it works using \n. But for it to show up in the output, need to use two \n.
```
stdin_str = "auth {{identifier_tls_alpn}} {{raw_proof}}"
stdin_str = """auth {{identifier_tls_alpn}} {{raw_proof}}
"""
stdin_str = "auth {{identifier_tls_alpn}} {{raw_proof}}\n"
string(61) "auth test2.dbq.no ggC1Dpj9bmFlRZbRIw8dtpPRNFNVABMFK73xbTfohX0"

stdin_str = "auth {{identifier_tls_alpn}} {{raw_proof}}\n\n"
string(62) "auth test2.dbq.no V9j76FOJkumY8pAS4C-ho1jEZA4d8bLGDJsGySVxUcs
"
```
The built-in part, was to output a newline at end of stdin_str automatically. 
But I guess this is specific to how ualpn works.

**Comment by jcgruenhage** [comment]
A bit late to the party, but wouldn't it make sense to have only one format of proof, and then use filters for converting between the formats?

**Comment by breard-r** [comment]
> A bit late to the party, but wouldn't it make sense to have only one format of proof, and then use filters for converting between the formats?

That's what I initially thought yes. I was planning to add a base64 minijinja filter so you can write something like `{{ proof | base64('url-nopad') }}`. Then I realized that proofs a treated different ways depending on the challenge. For `http-01`, it makes little sens to convert the proof since you have to serve it as-is. Same thing for `dns-01` but for the SHA-256 of the proof that has to be encoded using base64-url-nopad. The only case where it make sense to being able to convert it is `alpn-01` since you have to use it to build a certificate. That's why at first, instead of passing the proof itself, I passed the string for the entire acmeIdentifier extension. That was not a good choice since it restricts how you can integrate responders other than tacd.

In the end I think the correct solution would be, for `alpn-01` only, to pass the proof itself as a byte array that you can format using filters, but that would require a little work and, obviously, a breaking change. Adding a new field didn't break anything, quickly solves the issue and it may eventually be removed as part of the breaking change that would introduce the proof as a byte array.
