### ISSUE TITLE
dns-01 delay for worldwide TXT record propagation 

### ISSUE THREAD

**Issue by puphubv** [breard-r/acmed#156]
I haven't completely reviewed the code, but it seems that a dns-01 challenge delay parameter might be an appropriate addition.

Let me explain my understanding, which may not be perfectly accurate.

It's my understanding that Let's Encrypt will check name servers around the world, instead of JUST your  authoritative name server...

Meaning, you MUST add a delay, after your name servers have added the TXT record before you have Let's Encrypt check for the information to propagate around the world.  You can check the TXT record propagation at:

https://dnschecker.org/#TXT/_acme-challenge.<domain-name>

Here's a link where some of this has been discussed:

https://community.letsencrypt.org/t/dns-01-challenge-state-transition-pending-to-state-failed-too-short/95881/5

When using certbot, the solution I used successfully was to add a delay to my auth hook to sleep for 15 to 30 minutes.

Would that be the best thing to do with acmed?

**Comment by breard-r** [comment]
> It's my understanding that Let's Encrypt will check name servers around the world, instead of JUST your authoritative name server...

This should not be a problem since you should configure a TTL much shorter than the certificate renewal. With a short-enough TTL, any DNS resolver must retrieve the entry from the authoritative server since their cache is expired.

Aside from this issue with improper TTLs, the main issue the the time taken by the authoritative name server to update after you changed the DNS entry. Some ACME clients may change the DNS entry and immediately consider the DNS entry as publicly updated, while in fact the authoritative server may took a few minutes to update. This is why you usually need a delay for the dns-01 challenge.

> Would that be the best thing to do with acmed?

This should be handled by a hook. ACMEd won't notice the AC until the hooks returns, so you can simply add a hook that launches the `sleep` command for the desired amount of time. Or you can write a hook that checks the DNS records and won't return until it is actually updated (beware the cache issue).

**Comment by puphubv** [comment]
Handling this in the auth.sh script will work well.   I'll mention this in the wiki.
