### ISSUE TITLE
Use as a library

### ISSUE THREAD

**Issue by axos88** [breard-r/acmed#16]
Hi,

Can this be used as a library to set up, generate the challanges and download the certificates?
I used to use onur's acme package, but it doesn't support acme v2 unfortunately.

I have my own (rust) server running, and I made calls to the library to know which challanges to serve when the boulder server was verifying the challanges, and after that was done, i made another call to the library to get the signed certificate data.

It seems acmed is a standalone app, but can it be used as a library as well?

**Comment by breard-r** [comment]
Hi!

Unfortunately, ACMEd cannot be used as a library and there is no plan to do so. Maybe you should have a look at [acme-lib](https://crates.io/crates/acme-lib), that's the library I used before.

**Comment by axos88** [comment]
Awesome, looks good. Thanks!

**Comment by axos88** [comment]
I wonder why it's not listd on the letsencrypt website though.

**Comment by breard-r** [comment]
Well, as stated at the bottom of the [ACME Client Implementations page](https://letsencrypt.org/docs/client-options/), you can creates a PR on [the website's repository](https://github.com/letsencrypt/website) in order to request the inclusion of an implementation. Therefore, I guess nobody took the time to request its inclusion.
