### ISSUE TITLE
Compilation instruction on Alpine

### ISSUE THREAD

**Issue by YanTHIERY** [breard-r/acmed#21]
Hi,

i come with a good first issue, i want to list necessary packages to compile Acmed on Alpine Linux in README file;

- `openssl-dev` to avoid compilation problem with openssl crate
- `alpine-sdk` similar to debian-essentials
- `git` of course
- `rust`
- `cargo`

**Comment by breard-r** [comment]
Hey!

Since git isn't required (build from the release's tarball) and rustc/cargo are not in Alpine's packages, I would only keep the `openssl-dev` and `alpine-sdk` ones. However, the compilation on Alpine Linux is currently broken due to rust-lang/rust#40174. Hence, I don't think that's a good idea to include Alpine Linux guidelines until it's fixed.

**Comment by jpastuszek** [comment]
I just built it on alpine 3.11. It fails on 3.10 with the musl target issue.

```
apk add cargo git openssl-dev alpine-sdk
git clone https://github.com/breard-r/acmed.git
cd acmed
make
make install
```

**Comment by breard-r** [comment]
This is expected to fail since ACMEd requires Rust 1.36.0 or later and Alpine 3.10 package is 1.34.2. As you stated, on Alpine 3.11 it works because the Rust package is 1.39.0.

The other option to compile on Alpine is to install Rust 1.44 or later using rustup. Yes, Using rustup on Alpine requires a more recent version of Rust (see rust-lang/rust#40174).

**Comment by breard-r** [comment]
Since compilation instructions on Alpine are now included in the README and kept up to date, I guess I can close this issue.
