### ISSUE TITLE
Providing static linked binaries

### ISSUE THREAD

**Issue by holdenger** [breard-r/acmed#4]
Hey @breard-r 

Thank you for your effor in acmed. It's a nice peace of software. However, can you please consider providing static linked binaries (including libc and openssl)? I would like to use acmed on CentOS6 and there is some problem in OpenSSL version (since i'm a total rust noob i can't even install rust tools env).

**Comment by breard-r** [comment]
Hello!

Uploading statically linked binaries would mean that I have to maintain them and upload new ones each time OpenSSL has a vulnerability, which is [several times a year](https://www.openssl.org/news/vulnerabilities.html). I don't think I should/can have this kind of responsibility. Furthermore, if I was to do so, I would limit it to stable releases; and currently there is none of those.

In a more technical point of view, it may be possible to create such binaries since, in one hand, the openssl crate has a "vendored" feature that statically links OpenSSL and, in the other hand, Rust has [targets](https://forge.rust-lang.org/platform-support.html) which uses a statically linked musl. Unfortunately, even if it does work on small test projects, I couldn't reproduce it with ACMEd. I think it's due to a specific dependency which prevent the "vendored" feature to propagate to its own dependencies. Anyway, I think I should spend time on cleaning and improving the code first (seriously, at some point I went sloppy and created a mess…), and only then solve this compilation mystery.

As for this issue, I think it should be keep opened so I remember to fix the static compilation some day.

**Comment by breard-r** [comment]
By the way, if I was you I would create a CentOS6 virtual machine and install [rustup](https://rustup.rs/) on it. Rustup will take care of installing one (or several) versions of rust for one (or multiple) targets. Very useful for cross-compilation and tests on different rust version, but in your case you can keep the defaults and simply use it as a basic Rust installer.

**Comment by holdenger** [comment]
Thanks, i will try to build it with this: https://github.com/emk/rust-musl-builder

**Comment by breard-r** [comment]
I updated the build system and was able to generate statically linked binaries. Here is how I processed on my system :

1. Install musl
2. Use rustup
3. Add the target: `rustup target add "x86_64-unknown-linux-musl"`
4. Compile ACMEd: `make FEATURES="openssl_vendored" TARGET="x86_64-unknown-linux-musl"`
5. Install into a directory (useful for packaging): `make DESTDIR="my_package_directory" TARGET="x86_64-unknown-linux-musl" install`

Since building such binaries is now an easy task, I'm closing this issue. Feel free to reopen it if you have any question regarding this matter.
